name: CI
on: [push]

jobs:
  test:
    name: Test
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - name: Install
      run: echo "$GITHUB_CONTEXT"
    - name: Install
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test:unit
    - name: Build
      run: yarn build
    
  build:
    name: Build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - name: Install
      run: yarn
    - name: Build
      run: yarn build
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist
     
  deploy:
    name: Deploy
    needs: build
    if: success() && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
            node-version: '10.x'
      - name: Install Firebase Functions
        run: |
          cd ./functions
          yarn
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
