name: CI
on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - uses: actions/cache@v1
      id: cache
      with:
        path: node_modaules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
    - name: Install
      if: steps.cache.outputs.cache-hit != true
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test:unit
    
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - uses: actions/cache@v1
      id: cache
      with:
        path: node_modaules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
    - name: Install
      if: steps.cache.outputs.cache-hit != true
      run: yarn
    - name: Build
      run: yarn build
